### ISSUE TITLE
Blue team abilities are missing executors

### ISSUE THREAD

**Issue by alshaboti** [mitre/training#103]
I went through the training for `User Certificate`, and when I reached the flag 24 [Blue operation](https://user-images.githubusercontent.com/17414254/94550243-e5a10700-02af-11eb-89a1-61d27a5e71dd.png), Caldera process was complaining about missing `executor` see [here](https://user-images.githubusercontent.com/17414254/94550393-2436c180-02b0-11eb-9c62-ab4c830e8e37.png) in the `incident responder` profile. 

When I investigated this, I found the following: 

1. All `incident responder` abilities are missing the executor part, see for example the [Suspicious URLs in mail](https://user-images.githubusercontent.com/17414254/94550627-898ab280-02b0-11eb-80e9-f23200393b1a.png). In fact, it seems that all abilities in are missing the `executor`.  
2. Most of the abilities only support `Windows` and not `Linux`, when I run it in `Linux`  the operation is stuck at `Suspicious URLs in mail` ability and doesn't go beyond that, see [here](https://user-images.githubusercontent.com/17414254/94551117-572d8500-02b1-11eb-84e5-fc73aafac90b.png), and the Server complains about the executor. 

Setup: `Caldera version 2.8.0-909597268607e7cbca77bd22c462fb22` in `Docker  version 18.09.7` in `Ubuntu 16.04`, the blue agent is running via sudo in the host. 

Is this part of the training, should I fix the executors (I tried for the suspicious URLs, but still I am getting the same error).

**Comment by wbooth** [comment]
Thanks -- yea saw that, too. we'll address

**Comment by alshaboti** [comment]
Hi @wbooth I am passionate about this project and I'd like to contribute if you can help point to me where to look for this bug. 
It seems like the abilities are correct, but when they are loaded somehow the executors are missed. 

Thank you

**Comment by wbooth** [comment]
@alshaboti thanks for the offer we have other things that would be helpful to fix if you're interested, 
The executors was a sort of interesting bug here is the change for it: https://github.com/mitre/caldera/pull/1914/files

**Comment by alshaboti** [comment]
@wbooth I have finished the training (blue and user one), so I think I do have the basics to make some contributions. 
Please let me know how can I help, Thanks!
