### ISSUE TITLE
Blue Cert - Manual Flag 15 No abilities shown to complete the flag

### ISSUE THREAD

**Issue by blackb3lt** [mitre/training#128]
**Describe the bug**
The bug appears when you need to complete the flag 15 under manual "FIND CHANGES TO POWERSHELL PROFILE". The abilities to complete this flag are not present in the operations. Also the abilities some times are the same when you click "+potential links" it shows 2-3 times the same ability or shows abilities for Linux in even if the agent is for windows. Also the ability to complete the flag 16 is not present as well.

**To Reproduce**
1.Run a blue Golang agent elevated for windows & a red agent for windows
2. Start Manual operation and try to find the ability down below.
3. After completing flag 14 in the blue cert under manual flag 15 appears, and at this time you need to run the ability 930236c2-5397-4868-8c7b-72e294a5a376 to complete the flag where is not present.

**Expected behavior**
Some abilities not present, abilities may shown 2-3 time the same commands, Linux abilities even if the agent is for windows, 

**Screenshots**
![caldera-error](https://user-images.githubusercontent.com/62677185/120938029-7ec6ce00-c719-11eb-9929-666622cfcf15.PNG)

Same abilities shown 3 times
**Desktop (please complete the following information):**
 - OS: Kali Linux & Ubuntu 20.4
 - Browser [Chrome]
 - Version [Linux kali 5.9.0-kali1-amd64 #1 SMP Debian 5.9.1-1kali2 (2020-10-29) x86_64 GNU/Linux]

**Additional context**

**Comment by blackwidow0616** [comment]
I am looking into this, and I will get back to you as soon as I have more information.

**Comment by blackb3lt** [comment]
Sure! Let me know if you need any further information/details about the issue.

**Comment by mrengstrom** [comment]
@blackb3lt which caldera version are you running (tag or commit hash works)?  And are all the plugin checkouts the pinned versions for that caldera checkout (only important to tagged versions)?

That ability only has a single replacement variable field, so multiple copies should only differ in the `Path` which it looks like they don't, being exact copies.  I am going to check into reproducing this and see if I see the same behavior on the v3.1.0 caldera release and track down the issue.

**Comment by wbooth** [comment]
If you haven't resolved the issue on our own please re-open this issue or start a new one, thanks!
