### ISSUE TITLE
Certification Path is not persistent 

### ISSUE THREAD

**Issue by jemaiah** [mitre/training#130]
If we don't finish all the training in the same session, all the progress is lost.
and for example we have a step named mock to enable a mock module, but this step require a restart of the server. after the restart all the progress is lost and we need to start again from the begening.
the application should store the progress of training over sessions and even after a  restart.

**Comment by wbooth** [comment]
Thanks, going to leave this one up, we won't have an immediate solution for it but will add it to our backlog

**Comment by blackwidow0616** [comment]
CALDERA writes the training data to disk when the server is closed, generally using Ctrl+C. As long as the server is not being force killed, the training data should be retained on the next startup. However, if the server is being started with the --fresh flag, the data will be cleared and therefore not persist.

**Comment by blackwidow0616** [comment]
Hopefully this resolves your issue. If you’re still having any problems, please feel free to re-open or start a new ticket. Thanks!
