### ISSUE TITLE
Task #11 (Create Ability) not marked as complete despite following solution guide

### ISSUE THREAD

**Issue by deetee1** [mitre/training#131]
Hi, I'm going through the training plugin and all's good so far. I'm now at Task 11 and have followed the solution guide step by step (please refer to screenshots):

![image](https://user-images.githubusercontent.com/62365248/130307546-94f98913-75d5-4dba-8a93-c90e0a1281ed.png)
![image](https://user-images.githubusercontent.com/62365248/130307552-64eaf6ff-3614-4852-bd1f-a1c24833a307.png)
![image](https://user-images.githubusercontent.com/62365248/130307564-c91cc098-bae6-4a35-979c-490b6397374e.png)
![image](https://user-images.githubusercontent.com/62365248/130307571-ae281f09-522e-46a0-bdc4-1c4c0587c765.png)

However, task 11 is still not marked as complete. Am I missing something?

**Comment by iguannalin** [comment]
Is this the training flag to create a new ability? The flag might still be incomplete because it's searching for the exact name 'My test ability.'

**Comment by deetee1** [comment]
I tried "My test ability", and it worked! thank you so much
