### ISSUE TITLE
Unable to compile training module

### ISSUE THREAD

**Issue by 0xd3vnull** [mitre/training#143]
**Describe the bug**

Installation of training module throws error referencing airbnb-base

**To Reproduce**

Running the following...

Caldera Version: 4.0.0-alpha
NPM version: 8.1.0
node version: 16.13.0

Following steps, I have run 

```npm ci```

followed by 

```npm run init```

 from /opt/caldera/plugin/training

It throws the following error...

```
> lint
> eslint ./static/js/*.js


Oops! Something went wrong! :(

ESLint: 8.3.0

ESLint couldn't find the config "airbnb-base" to extend from. Please check that the name of the config is correct.

The config "airbnb-base" was referenced from the config file in "/opt/caldera/.eslintrc.js".

If you still have problems, please stop by https://eslint.org/chat/help to chat with the team.
```

have also tried running the command 

```npm run lint -- --fix```

 without success.

**Expected behavior**

Installation of training module

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac, Windows, Kali]
 - Version [e.g. 2.8.0]

**Additional context**

**Comment by 0xd3vnull** [comment]
Also, whenever I click on the "Solution Guide" I get the following error...

```Certificate does not exist```

I believe this is likely caused by the plugin not completed installation.

**Comment by uruwhy** [comment]
The training module isn't something that you need to "install". Simply include it in your list of enabled plugins within your configuration yaml file and start the server up. You should then see the training plugin appear in your list of available plugins after logging into the GUI, and from there you can begin using it.

**Comment by 0xd3vnull** [comment]
There is a comment on the master branch for the same issue (https://github.com/mitre/caldera/issues/2274) in which the way to resolve was to make sure that GoLang >1.11. This comment was closed before confirmation of resolution by the person who raised the issue.

I am having the same issue and can confirm
My version of GoLang is > 1.11

**Comment by uruwhy** [comment]
The issue you linked doesn't have anything to do with npm or "compiling" the training plugin, as far as I can tell. I'm not sure what you're trying to do with npm, but you don't need to do any of that in order to use the training plugin.

**Comment by 0xd3vnull** [comment]
I completely deleted and reinstalled caldera, and continue to get the same error.

It looks like this
![caldera-certificate](https://user-images.githubusercontent.com/90880891/144089664-acfebbe1-f65b-4d25-b7ab-bcc2ed6e74fe.png)

**Comment by uruwhy** [comment]
Can you verify the following, please?

- The git commit hash for your training plugin (`cd` into your training plugin directory and run `git rev-parse HEAD`)
- When running the server with the training plugin enabled and debug logging verbosity, can you verify that the training plugin is loaded correctly? The plugin load output looks something like `2021-12-01 16:31:31 - INFO  (app_svc.py:108 load) Enabled plugin: training`
- Within the training plugin, can you verify that you have the following file: `data/certifications/8da8f0b3-194a-4eed-95b0-43c1f1b64091.yml`

**Comment by 0xd3vnull** [comment]
- The git commit hash for your training plugin (cd into your training plugin directory and run git rev-parse HEAD)

```
[devnull@localhost training]$ git rev-parse HEAD
ffb14855bb27e406731a9793833366f66f0eb553
```

- When running the server with the training plugin enabled and debug logging verbosity, can you verify that the training plugin is loaded correctly? The plugin load output looks something like 2021-12-01 16:31:31 - INFO (app_svc.py:108 load) Enabled plugin: training

![image](https://user-images.githubusercontent.com/90880891/144528901-1a5f8f4f-5c41-4e48-a594-ba4df8c04370.png)

- Within the training plugin, can you verify that you have the following file: data/certifications/8da8f0b3-194a-4eed-95b0-43c1f1b64091.yml

```
[devnull@localhost caldera]$ cd plugins/training/data/certifications/
[devnull@localhost certifications]$ ls -la
total 8
drwxr-xr-x. 2 devnull devnull  102 Nov 30 23:33 .
drwxr-xr-x. 6 devnull devnull   80 Nov 30 23:33 ..
-rw-r--r--. 1 devnull devnull  987 Nov 30 23:33 8da8f0b3-194a-4eed-95b0-43c1f1b64091.yml
-rw-r--r--. 1 devnull devnull 1281 Nov 30 23:33 9cd5f3a0-765d-45bc-85c2-bc76d4282599.yml
````

**Comment by uruwhy** [comment]
Are all the necessary pip packages from requirements.txt installed correctly?

I tried using different browsers as well as different versions of python, and I'm not getting your same error, even on a fresh caldera installation on a completely different machine.

**Comment by uruwhy** [comment]
It look like it could be an aiohttp version issue. Can you run `pip show aiohttp` to see what version of aiohttp you have running? It looks like with v3.6.2 I get the same error, but with v3.8.1 it should work. You can run `pip install --upgrade aiohttp` to update the package.
