### ISSUE TITLE
Blue certificate: manual operation: "detect malicious file on system" not creating malicious_files.txt

### ISSUE THREAD

**Issue by kenvb** [mitre/training#163]
So i'm on exercise 2 of the "manual" section (the flag check for this is blue_2a.py https://github.com/mitre/training/blob/master/app/flags/manual/blue_2a.py)
And it claims to create a "pretend malicious file" and "malicious_files.txt" within a minute so i can run a manual operation.

1) The file(s) do(es) not get created. I have an active red client in the "cert-win" category so it should work.
2) After a while i created the file myself, like we were asked in "malicious file on system" in the autonomous section. and created a potential link "acquire suspicious files" in my "Blue Manual" operation. The "malicious_files" file got found and deleted, but still the flag doesn't get acquired.

Am i misunderstanding this exercise ? or what am i doing wrong ? Also, is the "acquire suspicious files" ability supposed to remove files automatically?

**Comment by elegantmoose** [comment]
@kenvb - did you resolve this? (sorry for tardy reply)
