### ISSUE TITLE
Manx UDP Mode Not Available

### ISSUE THREAD

**Issue by taschultz** [mitre/training#50]
This probably also needs to be an issue for Manx itself, but the Manx UDP mode is not available in release 2.6.6.  Only TCP options are displayed in the "deploy an agent" UI. Modifying the reverse-shell agent for ubuntu to contact="udp" will run, but Caldera does not recognize the communication method (shows "unknown"). 

![image](https://user-images.githubusercontent.com/12669524/78188620-2cfc2700-7436-11ea-9d23-7e27b18ffd48.png)
![image](https://user-images.githubusercontent.com/12669524/78188636-338a9e80-7436-11ea-8a39-fec4df1f497e.png)

 
https://github.com/mitre/training/blob/master/app/flags/plugins/manx/flag_1.py

**Comment by privateducky** [comment]
Good catch. When deploying Manx in UDP mode, there are actually two parameters that you need to change in the command-- the contact and the socket address. In your example above, you swapped the contact to UDP but the agent is still using the TCP (default) socket address of :7010. 

You can view the UDP contact address in the Advanced tab. 

As you noticed though, this isn't immediately apparent - and is likely to trip more than a few people up. I went ahead and added a "variation" command to the Manx ability. Variations are a newish feature to CALDERA which allow you to specify a variety of similar commands in a single ability YML file. Here is the PR I just merged for this: https://github.com/mitre/manx/pull/9/files 

All agent variations will popular in the deploy agents box, so this will be available in v2.7.0 in the near future.
