### ISSUE TITLE
At Instructions to Readme for a more clear process

### ISSUE THREAD

**Issue by GanbaruTobi** [mitre/training#93]
In the GUI of Caldera, one can only see the instructions where to send the final flag to, if no certificate is selected.

It would be nice to have the line also here in the project readme and in the documentation:

"If you earn a code, send it to caldera@mitre.org. We will validate it and send back an authenticated code as proof of completion."

**Comment by wbooth** [comment]
Thanks added to the readme: https://github.com/mitre/training/pull/98
